# Generated by Django 6.0.7 on 2026-09-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('status', models.CharField(choices=[('новый', 'новый'), ('контакт установлен', 'контакт установлен'), ('переговоры', 'переговоры'), ('принимается решение', 'принимается решение'), ('заказ', 'заказ'), ('оплачено', 'оплачено')], default='новый', max_length=50, verbose_name='Статус')),
                ('responsible_manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответственный менеджер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_activity', models.DateField(auto_now=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['id'],
            },
        ),
    ]
