# Generated by Django 6.0.7 on 2026-09-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_calendarnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['id'], 'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
    ]
